### ISSUE TITLE
Creating a new repo sometimes fails due to a race condition

### ISSUE THREAD

**Issue by mayankkapoor** [overcastcloud/python-overcast.django#221]
If a new user registers, and adds a new source repo quickly enough, a race condition can occur. The source build might fail before the repo key and folder structure is generated.

```
[2015-12-30 04:02:30,167: INFO/Worker-16] ['git', 'ls-remote', u'https://403c716544f679c2420a7fde7dcfb8814546ff65@github.com/anshprat/keystone.git', u'refs/heads/master'] gave stdout: 830fcbdf719df5edce69
d427b5797d23d62f5204        refs/heads/master
.
[2015-12-30 04:02:30,168: INFO/Worker-16] ['git', 'ls-remote', u'https://403c716544f679c2420a7fde7dcfb8814546ff65@github.com/anshprat/keystone.git', u'refs/heads/master'] gave stderr: None.
[2015-12-30 04:02:30,169: INFO/MainProcess] Task aasemble.django.apps.buildsvc.tasks.poll_one[e1d3c9db-fd93-4337-b90c-9d3b2370f77f] succeeded in 1.94276008941s: None
[2015-12-30 04:02:34,914: INFO/Beat] Scheduler: Sending due task poll-very-frequently (aasemble.django.apps.buildsvc.tasks.poll_all)
[2015-12-30 04:02:36,163: INFO/Worker-10] ['git', 'clone', u'https://403c716544f679c2420a7fde7dcfb8814546ff65@github.com/anshprat/keystone.git', '-b', u'master', 'build'] returned with returncode 0.
[2015-12-30 04:02:36,163: INFO/Worker-10] ['git', 'clone', u'https://403c716544f679c2420a7fde7dcfb8814546ff65@github.com/anshprat/keystone.git', '-b', u'master', 'build'] gave stdout: Cloning into 'build'
...
.
[2015-12-30 04:02:36,164: INFO/Worker-10] ['git', 'clone', u'https://403c716544f679c2420a7fde7dcfb8814546ff65@github.com/anshprat/keystone.git', '-b', u'master', 'build'] gave stderr: None.
[2015-12-30 04:02:36,164: DEBUG/Worker-10] ['git', 'rev-parse', 'HEAD'], input=None, cwd='/tmp/tmplMut7B/build', override_env=None, discard_stderr=False
[2015-12-30 04:02:36,172: INFO/Worker-10] ['git', 'rev-parse', 'HEAD'] returned with returncode 0.
[2015-12-30 04:02:36,172: INFO/Worker-10] ['git', 'rev-parse', 'HEAD'] gave stdout: 830fcbdf719df5edce69d427b5797d23d62f5204
.
[2015-12-30 04:02:36,173: INFO/Worker-10] ['git', 'rev-parse', 'HEAD'] gave stderr: None.
[2015-12-30 04:02:36,248: DEBUG/Worker-10] Using <class 'aasemble.django.apps.buildsvc.pkgbuild.python.PythonBuilder'> to build
[2015-12-30 04:02:36,249: DEBUG/Worker-10] ['python', 'setup.py', '--version'], input=None, cwd='/tmp/tmplMut7B/build', override_env=None, discard_stderr=True
[2015-12-30 04:02:36,753: INFO/Worker-10] ['python', 'setup.py', '--version'] returned with returncode 0.
[2015-12-30 04:02:36,753: INFO/Worker-10] ['python', 'setup.py', '--version'] gave stdout: 2015.1.3.dev7304
.
[2015-12-30 04:02:36,753: INFO/Worker-10] ['python', 'setup.py', '--version'] gave stderr: .
[2015-12-30 04:02:36,800: DEBUG/Worker-10] ['python', 'setup.py', '--name'], input=None, cwd='/tmp/tmplMut7B/build', override_env=None, discard_stderr=True
[2015-12-30 04:02:37,317: INFO/Worker-10] ['python', 'setup.py', '--name'] returned with returncode 0.
[2015-12-30 04:02:37,317: INFO/Worker-10] ['python', 'setup.py', '--name'] gave stdout: keystone
.
[2015-12-30 04:02:37,317: INFO/Worker-10] ['python', 'setup.py', '--name'] gave stderr: .
[2015-12-30 04:02:37,357: DEBUG/Worker-10] Detecting Build dependencies
[2015-12-30 04:02:37,358: INFO/Worker-10] Build dependencies: python-all, dh-python, python-setuptools, python-all-dev
[2015-12-30 04:02:37,358: DEBUG/Worker-10] Detecting run-time dependencies
[2015-12-30 04:02:37,359: INFO/Worker-10] Runtime dependencies: ${python:Depends}
[2015-12-30 04:02:37,359: DEBUG/Worker-10] Populating debian dir
[2015-12-30 04:02:37,359: DEBUG/Worker-10] ['python', 'setup.py', '--name'], input=None, cwd='/tmp/tmplMut7B/build', override_env=None, discard_stderr=True
[2015-12-30 04:02:37,869: INFO/Worker-10] ['python', 'setup.py', '--name'] returned with returncode 0.
[2015-12-30 04:02:37,869: INFO/Worker-10] ['python', 'setup.py', '--name'] gave stdout: keystone
.
[2015-12-30 04:02:37,869: INFO/Worker-10] ['python', 'setup.py', '--name'] gave stderr: .
[2015-12-30 04:02:37,870: DEBUG/Worker-10] Processing /var/lib/pkgbuilder/aasemble/django/apps/buildsvc/pkgbuild/../templates/buildsvc/debian
[2015-12-30 04:02:37,873: DEBUG/Worker-10] ['python', 'setup.py', '--name'], input=None, cwd='/tmp/tmplMut7B/build', override_env=None, discard_stderr=True
[2015-12-30 04:02:38,291: INFO/MainProcess] Received task: aasemble.django.apps.buildsvc.tasks.poll_all[6e75b0a0-4d87-48fa-9e4f-2d3f6d886ab3]
[2015-12-30 04:02:38,350: INFO/MainProcess] Task aasemble.django.apps.buildsvc.tasks.poll_all[6e75b0a0-4d87-48fa-9e4f-2d3f6d886ab3] succeeded in 0.0570371458307s: None
[2015-12-30 04:02:38,379: INFO/Worker-10] ['python', 'setup.py', '--name'] returned with returncode 0.
[2015-12-30 04:02:38,380: INFO/Worker-10] ['python', 'setup.py', '--name'] gave stdout: keystone
.
[2015-12-30 04:02:38,380: INFO/Worker-10] ['python', 'setup.py', '--name'] gave stderr: .
[2015-12-30 04:02:38,383: DEBUG/Worker-10] ['python', 'setup.py', '--name'], input=None, cwd='/tmp/tmplMut7B/build', override_env=None, discard_stderr=True
[2015-12-30 04:02:38,894: INFO/Worker-10] ['python', 'setup.py', '--name'] returned with returncode 0.
[2015-12-30 04:02:38,894: INFO/Worker-10] ['python', 'setup.py', '--name'] gave stdout: keystone
.
[2015-12-30 04:02:38,894: INFO/Worker-10] ['python', 'setup.py', '--name'] gave stderr: .
[2015-12-30 04:02:38,894: DEBUG/Worker-10] ['python', 'setup.py', '--version'], input=None, cwd='/tmp/tmplMut7B/build', override_env=None, discard_stderr=True
[2015-12-30 04:02:39,376: INFO/Worker-10] ['python', 'setup.py', '--version'] returned with returncode 0.
[2015-12-30 04:02:39,377: INFO/Worker-10] ['python', 'setup.py', '--version'] gave stdout: 2015.1.3.dev7304
.
[2015-12-30 04:02:39,377: INFO/Worker-10] ['python', 'setup.py', '--version'] gave stderr: .
[2015-12-30 04:02:39,379: INFO/Worker-10] New changelog entry: keystone (2015.1.3.dev7304+1) jiocloud; urgency=medium

  * Automatically built.
    SHA: 

 -- aaSemble Package Builder <pkgbuild@aasemble.com>  Wed, 30 Dec 2015 04:02:39 +0000


[2015-12-30 04:02:43,336: INFO/MainProcess] Received task: aasemble.django.apps.buildsvc.tasks.poll_one[00c53529-49e0-4607-88ba-0a9f690a8b1c]
[2015-12-30 04:02:43,369: INFO/MainProcess] Received task: aasemble.django.apps.buildsvc.tasks.poll_one[eb3afb70-0ef3-4cd7-9aab-304c32eb636b]
[2015-12-30 04:02:44,669: INFO/Worker-18] ['git', 'ls-remote', u'https://github.com/akash1808/nova', u'refs/heads/package-builder'] returned with returncode 0.
[2015-12-30 04:02:44,669: INFO/Worker-18] ['git', 'ls-remote', u'https://github.com/akash1808/nova', u'refs/heads/package-builder'] gave stdout: 92b3b3708749a8553664b1f4a0d21611cf82934d       refs/heads/package-builder
.
[2015-12-30 04:02:44,669: INFO/Worker-18] ['git', 'ls-remote', u'https://github.com/akash1808/nova', u'refs/heads/package-builder'] gave stderr: None.
[2015-12-30 04:02:44,670: INFO/MainProcess] Task aasemble.django.apps.buildsvc.tasks.poll_one[00c53529-49e0-4607-88ba-0a9f690a8b1c] succeeded in 1.33298956137s: None
[2015-12-30 04:02:44,991: INFO/Beat] Scheduler: Sending due task poll-very-frequently (aasemble.django.apps.buildsvc.tasks.poll_all)
[2015-12-30 04:02:45,339: INFO/Worker-19] ['git', 'ls-remote', u'https://403c716544f679c2420a7fde7dcfb8814546ff65@github.com/anshprat/keystone.git', u'refs/heads/master'] returned with returncode 0.
[2015-12-30 04:02:45,339: INFO/Worker-19] ['git', 'ls-remote', u'https://403c716544f679c2420a7fde7dcfb8814546ff65@github.com/anshprat/keystone.git', u'refs/heads/master'] gave stdout: 830fcbdf719df5edce69d427b5797d23d62f5204        refs/heads/master
.
[2015-12-30 04:02:45,339: INFO/Worker-19] ['git', 'ls-remote', u'https://403c716544f679c2420a7fde7dcfb8814546ff65@github.com/anshprat/keystone.git', u'refs/heads/master'] gave stderr: None.
[2015-12-30 04:02:45,340: INFO/MainProcess] Task aasemble.django.apps.buildsvc.tasks.poll_one[eb3afb70-0ef3-4cd7-9aab-304c32eb636b] succeeded in 1.96850141417s: None
[2015-12-30 04:02:46,179: ERROR/MainProcess] Task aasemble.django.apps.buildsvc.tasks.build[a39c8ff6-6625-42aa-a0c6-bb4086c692b0] raised unexpected: DbuildSourceBuildFailedException('Source build FAILED',)
Traceback (most recent call last):
  File "/var/lib/pkgbuilder/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/pkgbuilder/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/lib/pkgbuilder/aasemble/django/apps/buildsvc/tasks.py", line 22, in build
    ps.build_real()
  File "/var/lib/pkgbuilder/aasemble/django/apps/buildsvc/models.py", line 343, in build_real
    builder.build()
  File "/var/lib/pkgbuilder/aasemble/django/apps/buildsvc/pkgbuild/__init__.py", line 58, in build
    self.docker_build_source_package()
  File "/var/lib/pkgbuilder/aasemble/django/apps/buildsvc/pkgbuild/__init__.py", line 96, in docker_build_source_package
    proxy=settings.AASEMBLE_BUILDSVC_BUILDER_HTTP_PROXY)
  File "/var/lib/pkgbuilder/venv/local/lib/python2.7/site-packages/dbuild/__init__.py", line 197, in docker_build
    'Source build FAILED')
DbuildSourceBuildFailedException: Source build FAILED
[2015-12-30 04:02:48,432: INFO/MainProcess] Received task: aasemble.django.apps.buildsvc.tasks.poll_all[b4bea070-126a-4e38-bd57-7ecc49850f8e]
[2015-12-30 04:02:48,507: INFO/MainProcess] Task aasemble.django.apps.buildsvc.tasks.poll_all[b4bea070-126a-4e38-bd57-7ecc49850f8e] succeeded in 0.0723413918167s: None
[2015-12-30 04:02:51,465: INFO/Worker-9] ['gpg', '--batch', '--gen-key'] returned with returncode 0.
[2015-12-30 04:02:51,466: INFO/Worker-9] ['gpg', '--batch', '--gen-key'] gave stdout: gpg: skipping control `%%commit' ()
.......+++++
+++++
.++++++++++..++++++++++++++++++++..++++++++++..++++++++++++++++++++++++++++++++++++++++.+++++.......+++++...+++++.++++++++++++++++++++..+++++..+++++..++++++++++....+++++++++++++++++++++++++...+++++>.++++++++++.+++++..+++++....++++++++++.+++++++++++++++.+++++>.+++++>..+++++.........>..+++++...................................................<.+++++..............................................................>.+++++............................................................................................................................................+++++^^^
gpg: key 5EB512F0 marked as ultimately trusted
.
[2015-12-30 04:02:51,466: INFO/Worker-9] ['gpg', '--batch', '--gen-key'] gave stderr: None.
[2015-12-30 04:02:51,551: INFO/Worker-9] ['gpg', '-a', '--export', '5EB512F0'] returned with returncode 0.
[2015-12-30 04:02:51,551: INFO/Worker-9] ['gpg', '-a', '--export', '5EB512F0'] gave stdout: -----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQINBFaDVzoBEADcagk2qxj40NUwy/r/Z3b33sfgPVW8BxTSj/s1D4Aw7Qj+VrU/
K7zCqkP9iNQGcUREdbuIyC68FtPT3Ejj1IphyOLfsPU3ZtNz+CSI8u+WT1zkkThN
uPtuowMKfcGqwmP2vEqpciAP+JTQp1iWCc08748FBzDyq09woFRMOQ+lxgIEpCjj
wOsw8Am6UWy08Odb9Af8UKmjZIqnFhxfOVrI6aalHIF+XlFX1bc1d5Y/e/VxPH1o
/V06lqK4T66cgoZ8OE+QIPUdJTzx2vzcBsTnzuQU3zCSTDf4wTusKbk3CtGJqcLl
wOfZOWI2hUkSiw1uo9UItG4Y8QRhjMJ1P4ZOPC95t46S1ExuVIoK3Sg4tP64zASS
mUbDDeGHyn0K7aT3VNv2xXVOlvrVJWn02AxOCzYXMniQoG2Xpqd9quA0Bt+D9aFN
XZMKQXSiwyWEyzbhicJ0gsYnGw5X9q6GIvsOqHQYwK0dp6E+8QEk1nBJ9oZStEF4
Z/wATRCMZunJG+IX4k0Q883LMournUVx0o5gLJ3yoTOYyAQk0A3xKjYWgB0g7T2c
Sr89s0tmqtr76syou9/mamVVugWQGMdHSCTuwTAiVWM6kBSSIE+7xLwPDNGtzqje
+OyigmsVwyCICRnuNyxn9YjG7YCLBSJZGy3DjJFov3xYKqyyETpRzHwmRQARAQAB
tBNhbnNocHJhdCByZXBvc2l0b3J5iQI4BBMBAgAiBQJWg1c6AhsvBgsJCAcDAgYV
CAIJCgsEFgIDAQIeAQIXgAAKCRDMLV8yXrUS8E0GD/wLTAGqUa2j8YcKlS2AgWAj
KO2jRpkfZazVw8YL/VoBijF4OcwHjrH2SIPCO8cNDtwG5FSYH6LzsWShtHbn1g9H
L+9F+7CbIeVJR1+O9GX8R9cDJj1YTd3+r9ldBFMxS4wZ6ZLPQXkZRHV+E9R7oygM
mMH54Ep/DanbkWcknryJDGJqqIRzz2OS1tSSr02SBj9neVHVIfspxzugD16oBhoY
JX+cQo33oZ6o7uweD7rOBNqU0MbhVieUhwyy06o5xeeu6TN8ED7NjJbNue+3qeZp
1aVe+mnECqpHT4BE6vYafCksjmF40Dy3wvS5lJKP1rZVBiAXAalRO/18YqDbCQ9b
kFhiCd1w+v1SF6E61fdNGZlhHk0RpmzI0yT+eDDk3I/oPcIqgr9MSHHE96d/bjyR
Eu139Btz5sbJk+EmXEtzVaHv/w4zalpKeRdAh/Q9WETZNktKypMynb+HiwbRatQc
9eI08GjSyBvF9M6x/0jS3U2niyKL7pqP2WCe/+P6chsjdYaklFt22YRValKBHMeU
9LnjlDnkVhdoTvu4xPzc4CuTNuAfWLz+buN/vbw5MCLaOJDA+a3nH+dD4FqNtlTX
bFBew3nvhMjAmEDbetvhjEfkQ12W+ks8QFIc+n5zcbb1RYq+n39TYYa5TcGdNRh2
G7JH1LizvF31ueR61r+iwrkEDQRWg1c6EBAA2XmPUBu1LcLH1TGzzZsL6QuGIYV8
z6Xo/dpzGeSyG0EWOkVSp7ydR0GLNk8MWjLBfLE/GnYYx+REypeGQfY1/gyKe3U8
xNr//5NnsyyzW8o97kreDGIIvya391Jntlu+5/2KdvzqkUj6T8rzhSvzBiZbhoMw
j3ky/GtFH9LTfF0w8EOkbT1kqrUfc+J2XYXPsmgwJWYO3jjnDMbRVPyjnGWNSUog
sIe28do+q9g+amt8amrEVRHH2xWhjxrlRV3JXmNfnZLHiHHGM0IZBBsNqtoxCBLK
bRLuk8jvebRm/KdDzrAw3o2kSDLJWToBv7aODm94e9jW8335lzBsjMWAdLhKdqgT
aACcND62ATnHxXkhAShqJ+Q1pBNoMOVL1jsw/jY6EnuhOsoIJ9zows8nRGesZE5u
VgE+rdq2YcFJ+Vutvs8TseevXWF7rQFSsmnrGlYjP6Ey9K0DhLW6mUnigK5t4Pd9
bk4FCwSY+hcUt0TXAHWO/7L4dhFA0J4kKHO58E6ktwmHHZw8JUdHYJLPdt9ubX2P
O1h/IzWqSYC73Gb3qiMzN6dWP+gtvYAbs5pgJs1CnYaLxzNUjRiNQa1TemiejgpZ
uZHRcXIZuot8XT1FCiaEKBS3/VQEQ/cDHWL7NFQVGP41GIm8yfwtwiiF+ltuQ6yK
1QGgva1hj382P1cAAwUP/3+kqJpVDTlEqWz1uR1It/zJcXcxcDYRCt3VA/9rEg86
UO46xDeyDYXKhfS5pUkiRnJICTOHlrbbNkp3Vdx2oCW5slx7XGa5SYnnuPM/JV2b
wWwH8s86LNUz0DdA3eFV3Bfqrl8qKj357a7BbNLkw/upZlQprT4AG8qfo1qyV0mm
SyrL1vChZ6LvOU8xXNNmE/MSk4+UcOx2Bsre9J9QlGvZSi6D+hXGrPX9GPf1XUzh
yvlQa3iS6qG3ojVBARZQYqYwOzp2epPaLk4evrdNH/12SkCtTEeEIAg0qn7q69Gr
YEabSpZQLBzf+zVf6DsupnRxRwTBVqc9PsAyko1a4crG9sDh3t+AClk7e4gZguQ+
Bozu6X4UVyi5k9pan3sEbbntJODUEnlFSnAyB3w2nch7e044IrxX3j6sxz+fQKXa
aGmuFRSvQLbT5e/+kx6LjQg6xsv2CeB2+N/IRW/FKi4MgL3CYc7UldQb+16YtsuF
iKat1Tc0zIYLqBlrEeEZOgUyOqq+DsAGYD3wcwLOpljByhV2N4GhZQI719JxFeoE
PHi66vjo7wgIn/AKhNhtl6T7M5aIGad7+Um5IsDk9NEshmnT/1c5HY/sel6mujfj
2u5Fi3zqU4082pPGE2UKho1NhNz6+gNGZWKFOhlJkWnaBU8V9jMCQBq2x9f0YrAq
iQIfBBgBAgAJBQJWg1c6AhsMAAoJEMwtXzJetRLwOzEP/04OEjFBPHF4rHs2sXvm
xw4K9Cx+ddnQXJMhLKPyCpbu5eVnHZyTMs4tS9AP2ksjK1j8y5+nT4+LUQ6sdx23
UvSrbVafa4H2kE/4Pa5YyZRIQJwHv70vCcAF6IvRe6qCXrpnx0cWGl5I4Ykbdlpp
q0v4aXD3UejhnXzlK1mVhhf0sjEbvp8Zo2hcudx6+n1Syaq/ojBa0Q/Ed6qETeKE
/II04rlq2IAYuyoWULl5zKZ4sdDa+tJtFNINeXzoF3b2ycqpahq6wi/EYQn5Mrqz
2ZNYHBuog3JkV4QGqV8Nib20V2Mpgz4NiP/8Qs3ArC5PcOa5Lku5rzyxKTlY4ORI
9kDiiemftpRoAwUns6iOW2OP60Zu041JgpQS+hs95RBr2HFz6o9P5OKw9+FrQAnD
/G/h41gqMX+tiEgEBOjxcBPY/GUrPlQaQfiB2CKyvAoh+elxm9jmuUEDcuf5Zu8j
fzzECr5+r4Hqewm96gY6ktdeeJH9PHY7eBg9I2N94Qy43ulwsJXFPIMFrEQO99BG
m5FG6jOee1sqYwpIX8UDFPnff0kvNEN+MVSAfWv0IVgw8pp+OzBV0DU26ikXem3U
slUAop0z6/5xGZM/HP/v2BbNoeZYjXGXLCl76b36B3ozATeYmvGmMjEswquzfA50
aHPeSEh9DfarUXnsRlHFsK63
-----END PGP PUBLIC KEY BLOCK-----
.
[2015-12-30 04:02:51,552: INFO/Worker-9] ['gpg', '-a', '--export', '5EB512F0'] gave stderr: None.
[2015-12-30 04:02:52,061: INFO/Worker-9] ['reprepro', '-b', u'/var/lib/pkgbuilder/data/repos/anshprat/anshprat', 'export'] returned with returncode 0.
[2015-12-30 04:02:52,062: INFO/Worker-9] ['reprepro', '-b', u'/var/lib/pkgbuilder/data/repos/anshprat/anshprat', 'export'] gave stdout: .
[2015-12-30 04:02:52,062: INFO/Worker-9] ['reprepro', '-b', u'/var/lib/pkgbuilder/data/repos/anshprat/anshprat', 'export'] gave stderr: None.
[2015-12-30 04:02:52,063: INFO/MainProcess] Task aasemble.django.apps.buildsvc.tasks.export[5f1a7689-6269-4236-b30e-69f64d6a1c26] succeeded in 49.2967930147s: None
[2015-12-30 04:02:53,485: INFO/MainProcess] Received task: aasemble.django.apps.buildsvc.tasks.poll_one[6fbdf6ae-2b95-410b-bd1b-68297c06a68a]
[2015-12-30 04:02:53,519: INFO/MainProcess] Received task: aasemble.django.apps.buildsvc.tasks.poll_one[845fb786-fef1-4345-b1e3-04bb6c8090f0]
[2015-12-30 04:02:53,552: INFO/MainProcess] Received task: aasemble.django.apps.buildsvc.tasks.export[f4c40407-088f-4d8b-8cb4-6df065dd34fb]
[2015-12-30 04:02:53,766: INFO/Worker-24] ['reprepro', '-b', u'/var/lib/pkgbuilder/data/repos/anshprat/anshprat', 'export'] returned with returncode 0.
[2015-12-30 04:02:53,767: INFO/Worker-24] ['reprepro', '-b', u'/var/lib/pkgbuilder/data/repos/anshprat/anshprat', 'export'] gave stdout: .
[2015-12-30 04:02:53,767: INFO/Worker-24] ['reprepro', '-b', u'/var/lib/pkgbuilder/data/repos/anshprat/anshprat', 'export'] gave stderr: None.
[2015-12-30 04:02:53,768: INFO/MainProcess] Task aasemble.django.apps.buildsvc.tasks.export[f4c40407-088f-4d8b-8cb4-6df065dd34fb] succeeded in 0.213481577113s: None
[2015-12-30 04:02:54,890: INFO/Worker-23] ['git', 'ls-remote', u'https://github.com/akash1808/nova', u'refs/heads/package-builder'] returned with returncode 0.
[2015-12-30 04:02:54,890: INFO/Worker-23] ['git', 'ls-remote', u'https://github.com/akash1808/nova', u'refs/heads/package-builder'] gave stdout: 92b3b3708749a8553664b1f4a0d21611cf82934d       refs/heads/package-builder
```

**Comment by sorenisanerd** [comment]
Consider installing haveged on the server. This helps collect entropy which helps generate RSA keys much, much faster.
