### ISSUE TITLE
checkout fails if last_seen_revision is force pushed

### ISSUE THREAD

**Issue by anshprat** [overcastcloud/python-overcast.django#300]
if the revision in last_seen_reviosn has been force pushed upon, i.e, it no longer exists, then checkout fails..

[2016-01-28 06:11:41,285: INFO/Worker-4] Traceback (most recent call last):
[2016-01-28 06:11:41,285: INFO/Worker-4]   File "/usr/local/bin/aasemble-pkgbuild", line 9, in <module>
[2016-01-28 06:11:41,285: INFO/Worker-4]     load_entry_point('aasemble.django==0.1a', 'console_scripts', 'aasemble-pkgbuild')()
[2016-01-28 06:11:41,285: INFO/Worker-4]   File "/usr/local/lib/python2.7/dist-packages/aasemble.django-0.1a-py2.7.egg/aasemble/django/apps/buildsvc/pkgbuild/**init**.py", line 313, in main
[2016-01-28 06:11:41,285: INFO/Worker-4]     builder.checkout()
[2016-01-28 06:11:41,286: INFO/Worker-4]   File "/usr/local/lib/python2.7/dist-packages/aasemble.django-0.1a-py2.7.egg/aasemble/django/apps/buildsvc/pkgbuild/**init**.py", line 109, in checkout
[2016-01-28 06:11:41,286: INFO/Worker-4]     run_cmd(cmd, cwd=self.builddir, logger=self.logger)
[2016-01-28 06:11:41,286: INFO/Worker-4]   File "/usr/local/lib/python2.7/dist-packages/aasemble.django-0.1a-py2.7.egg/aasemble/django/utils.py", line 140, in run_cmd
[2016-01-28 06:11:41,286: INFO/Worker-4]     cmd, proc.returncode, final_output)
[2016-01-28 06:11:41,286: INFO/Worker-4] aasemble.django.exceptions.CommandFailed: ['git', 'reset', '--hard', u'80baeb6b32018e4d39e2bd13d0566aa5a0b1fe8a'] returned 128. stdout="fatal: Could not parse object '80baeb6b32018e4d39e2bd13d0566aa5a0b1fe8a'.\n"
[2016-01-28 06:11:41,326: INFO/Worker-4] 
[2016-01-28 06:11:41,326: INFO/Worker-4] ['aasemble-pkgbuild', 'checkout', u'http://192.168.10.10:8000/api/v3/builds/e8e79271-7c36-42f4-a51c-0b102ae55723/'] returned with returncode 1.
[2016-01-28 06:11:41,330: ERROR/MainProcess] Task aasemble.django.apps.buildsvc.tasks.build[17f450be-2168-4ed2-aee5-76efa9a858a6] raised unexpected: CommandFailed('[\'aasemble-pkgbuild\', \'checkout\', u\'http://192.168.10.10:8000/api/v3/builds/e8e79271-7c36-42f4-a51c-0b102ae55723/\'] returned 1. stdout=\'Traceback (most recent call last):\n  File "/usr/local/bin/aasemble-pkgbuild", line 9, in <module>\n    load_entry_point(\\'aasemble.django==0.1a\\', \\'console_scripts\\', \\'aasemble-pkgbuild\\')()\n  File "/usr/local/lib/python2.7/dist-packages/aasemble.django-0.1a-py2.7.egg/aasemble/django/apps/buildsvc/pkgbuild/**init**.py", line 313, in main\n    builder.checkout()\n  File "/usr/local/lib/python2.7/dist-packages/aasemble.django-0.1a-py2.7.egg/aasemble/django/apps/buildsvc/pkgbuild/**init**.py", line 109, in checkout\n    run_cmd(cmd, cwd=self.builddir, logger=self.logger)\n  File "/usr/local/lib/python2.7/dist-packages/aasemble.django-0.1a-py2.7.egg/aasemble/django/utils.py", line 140, in run_cmd\n    cmd, proc.returncode, final_output)\naasemble.django.exceptions.CommandFailed: [\\'git\\', \\'reset\\', \\'--hard\\', u\\'80baeb6b32018e4d39e2bd13d0566aa5a0b1fe8a\\'] returned 128. stdout="fatal: Could not parse object \\'80baeb6b32018e4d39e2bd13d0566aa5a0b1fe8a\\'.\\n"\n\'',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery-3.1.19-py2.7.egg/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery-3.1.19-py2.7.egg/celery/app/trace.py", line 438, in **protected_call**
    return self.run(_args, *_kwargs)
  File "/home/python-overcast.django/aasemble/django/apps/buildsvc/tasks.py", line 22, in build
    ps.build_real()
  File "/home/python-overcast.django/aasemble/django/apps/buildsvc/models.py", line 386, in build_real
    executor.run_cmd(['aasemble-pkgbuild', 'checkout', br_url], cwd=tmpdir, logger=br.logger)
  File "/home/python-overcast.django/aasemble/django/apps/buildsvc/executors.py", line 17, in run_cmd
    return run_cmd(_args, *_kwargs)
  File "/home/python-overcast.django/aasemble/django/utils.py", line 140, in run_cmd
    cmd, proc.returncode, final_output)
CommandFailed: ['aasemble-pkgbuild', 'checkout', u'http://192.168.10.10:8000/api/v3/builds/e8e79271-7c36-42f4-a51c-0b102ae55723/'] returned 1. stdout='Traceback (most recent call last):\n  File "/usr/local/bin/aasemble-pkgbuild", line 9, in <module>\n    load_entry_point(\'aasemble.django==0.1a\', \'console_scripts\', \'aasemble-pkgbuild\')()\n  File "/usr/local/lib/python2.7/dist-packages/aasemble.django-0.1a-py2.7.egg/aasemble/django/apps/buildsvc/pkgbuild/**init**.py", line 313, in main\n    builder.checkout()\n  File "/usr/local/lib/python2.7/dist-packages/aasemble.django-0.1a-py2.7.egg/aasemble/django/apps/buildsvc/pkgbuild/**init**.py", line 109, in checkout\n    run_cmd(cmd, cwd=self.builddir, logger=self.logger)\n  File "/usr/local/lib/python2.7/dist-packages/aasemble.django-0.1a-py2.7.egg/aasemble/django/utils.py", line 140, in run_cmd\n    cmd, proc.returncode, final_output)\naasemble.django.exceptions.CommandFailed: [\'git\', \'reset\', \'--hard\', u\'80baeb6b32018e4d39e2bd13d0566aa5a0b1fe8a\'] returned 128. stdout="fatal: Could not parse object \'80baeb6b32018e4d39e2bd13d0566aa5a0b1fe8a\'.\n"\n'

**Comment by pljensen** [comment]
Can you help me understand how this happened? How did the build get triggered?

**Comment by anshprat** [comment]
This was in a docker packagebuilder. I run celery without -B in docker as I use it only for checking my pkgbuilder changes. When celery is not running with -B, then the builds have to be done by rebuild option. And in that case the last seen revision no longer exists after a forced push, and such a "rebuild" fails.
